SELECT 
    A.TCK_ID
    , A.PRN_ID
    , A.PI_RP_ID
    , A.UPD_DT
    , A.CMP_DT
    , A.STR_PNT
    , A.PRN_FLG
    , B.ENG_NM AS DEV_NM
    , B.SPK_NM
    , COALESCE(C.PI_NUM,'Undefined') AS PI_NUM
    , COALESCE(C.ITR_ID,'Undefined') AS ITR_ID
    , COALESCE(C.ACT_FLG,FALSE) AS ACT_FLG
    , CASE WHEN D.TCK_STS NOT IN ('Done', 'TO DO') THEN 'In Progress' ELSE D.TCK_STS END AS TCK_STS
FROM `SILVER.FCT_DEV_EFRT` A
LEFT JOIN `SILVER.DIM_DEV_INF` B
ON A.DEV_ID = B.DEV_ID
LEFT JOIN (SELECT PI_ID,PI_NUM, ITR_ID, ACT_FLG FROM `SILVER.DIM_SPRINT_DT` GROUP BY ALL) C
ON A.PI_RP_ID = CONCAT('DDE ',C.PI_ID)
LEFT JOIN `SILVER.DIM_TCK_INF` D
ON A.TCK_ID = D.TCK_ID
WHERE 1=1
    AND D.TCK_STS NOT IN ('Backlog', 'Cancelled')
    AND PI_RP_ID !='Undefined'
